### ISSUE TITLE
Twizy SERV STOP ! Arrest

### ISSUE THREAD

**Issue by duedenis3** [dexterbg/Twizy-Cfg#1]
My twizy after completely discharging 12 V battery has stopped!
Disassembled the charger and verified voltages: 14.5 V OK, 36v present before the output relay.
bought the programmer for twizy but it does not work ... maybe the seller's scam? Incompatible?
do I have to reset the error codes to restore?how?
I ask you kindly if you can give me directions to solve the problem.
thank you very much,
Denis
denis.b@email.it
![charger connected key disconnected](https://user-images.githubusercontent.com/40168531/41234276-05cd77cc-6d8c-11e8-8405-08f467b2d52c.jpg)
![connected charger connected key](https://user-images.githubusercontent.com/40168531/41234277-05f2577c-6d8c-11e8-8021-830e179284eb.jpg)
![failed](https://user-images.githubusercontent.com/40168531/41234278-061530d0-6d8c-11e8-93d3-ed6586b8502f.jpg)
![obd2](https://user-images.githubusercontent.com/40168531/41234279-063c2ad2-6d8c-11e8-82c7-1f6dc3983bc1.jpg)

**Comment by dexterbg** [comment]
No recognizable relation to Twizy-Cfg. Please check the Twizy forums and ask the seller of your tool for help.
